export const APP_ACTION_TYPES = {
  SET_THEME: "SET_THEME",
  SET_TOKEN: "SET_TOKEN",
  SET_LANGUAGE: "SET_LANGUAGE",
  SET_USER_INFO: "SET_USER_INFO",
  SET_ROUTES: "SET_ROUTES",
  SET_ALL_STATE: "SET_ALL_STATE",
};
